<?php

namespace AppBundle\Repository;

/**
 * TestEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
